logging.level:
  org.springframework.web.servlet.DispatcherServlet: DEBUG
  org.springframework.data.elasticsearch: TRACE
  org.elasticsearch.client.RestClient: TRACE
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.zaxxer.hikari: TRACE
  org.hibernate.SQL: DEBUG
  org.hibernate.orm.jdbc.bind: TRACE
  org.springframework.web: DEBUG

spring.mvc:
  log-request-details: true

spring.jpa:
  open-in-view: false
  properties:
    hibernate:
      default_batch_fetch_size: 30
      show_sql: true
      format_sql: true
      use_sql_comments: true
      highlight_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # jpa ?/??? ??
  generate-ddl: true

core:
  security:
    oauth2:
      jwt-signing-key: 12345678901234567890123456789012
  client:
    common:
      decryptKey: "QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoxMjM0"
      encryptKey: "Rk5EX0ZORF8xMTA5X0RFVg=="
  datasource:
    default:
      write:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://tutorial-database-1.cd4y8y00gnoy.ap-northeast-2.rds.amazonaws.com/beads
        username: admin
        password: skarnddmstjs
      read:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://tutorial-database-1.cd4y8y00gnoy.ap-northeast-2.rds.amazonaws.com/beads
        username: admin
        password: skarnddmstjs

springdoc:
  swagger-ui:
    path: /kitten/swagger.html
    enabled: true
  api-docs:
    path: /kitten
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1095737006624-tbucpt82dee4ju1g4dg0kafcgbqisl2i.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "https://core-api.diykitten-backend.site/oauth2/callback/google"
#            redirect-uri: "http://localhost:8080/oauth2/callback/google"
          kakao:
            client-id: 81b6777f08a10e8e5fa70763d40385b3
            client-name: kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            redirect-uri: "http://localhost:8080/oauth2/callback/kakao"
          naver:
            client-id: mjaOVjhRIMMPBJsE_qT1
            client-secret: 1fT2FTnTOZ
            client-name: naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
            redirect-uri: "http://localhost:8080/oauth2/callback/naver"
          linkedin:
            client-id: 867mol0hcfdh3h
            client-secret: FxSwIrX0NYnhfEyj
            client-name: LinkedIn
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:8080/oauth2/callback/linkedin"
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/me
            user-name-attribute: id

aws.s3:
  aws-access-key-id: AKIA2UC3AUG77KT4FTOZ
  aws-secret-access-key: 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
  aws-bucket-name: mium-eunsun